### PR TITLE
Hotfix to fix C-Bill Calculations

### LINKED ISSUE #55: C-bill costs not displaying properly
It took me a bit to figure it out, but SSW seems to be having trouble with the Final C-bill cost calculation, or maybe just the display.  For instance. the HSN-10G Hellspawn

Item                                            DefBV     OffBV             Cost
Internal Structure - Endo Steel                 56         0           72,000.00
Engine - XL Fusion Engine                        0         0        3,240,000.00
Gyro - Gyro                                     23         0          900,000.00
Cockpit - Standard                               0         0          340,000.00
Heat Sinks - Double Heat Sink                    0         0           60,000.00
Musculature - Standard                           0        45           90,000.00
Actuators                                        0         0           45,000.00
Jump Jets - Standard Jump Jet                    0         0          225,000.00
Armor - Light Ferro-Fibrous                    318         0          112,500.00

Medium Pulse Laser                                  0        48        60,000.00
Medium Pulse Laser                                  0        48        60,000.00
MML-7                                               0        67       105,000.00
MML-7                                               0        67       105,000.00
Light PPC                                           0        88       150,000.00
@ MML-7 (SRM)                                       0         8        27,000.00
@ MML-7 (LRM)                                       0         8        30,000.00
@ MML-7 (LRM)                                       0         8        30,000.00

Cost Multiplier                                                            1.450
Dry Cost                                                               8,068,525
Total Cost                                                             8,068,525

As you can see, the Dry Cost and the Total Cost are the same. However, the Total Cost should be the Dry Cost plus the basic value of the ammunition.

A little note. Page 282 of TM states "As a general guide, when using these figures to compute a unit's final cost, it is not necessary to purchase ammunition for ammo-based weaponry." SSW follows this and doesn't include the cost of ammo when figuring out the Dry Cost of the design, but then is supposed to add it in to get the total cost.

This is a big difference between SSW and MegaMek. MM DOES include the ammo as part of the basic cost, and thus its multiplied by the Mech's cost modifier, so straight comparisons between the two programs isn't easy.

### PR DESCRIPTION
**Pull request by KaydenMiller**
* Updates TRO output for SSW and SAW
* Update Total C-Bill cost calculations
* Update output for PDF in SSW and SAW
* Add ammo cost to record sheets

Should fix #55

### CODE REVIEW

File: sswlib/src/main/java/components/CombatVehicle.java [hunk 1]
```diff
@@ -389,13 +389,12 @@ public int GetCurrentBV() {
...
-        // 8/7/2012 Commented out the GetAmmoCosts addition to match the way Mech works - GKB
-        return (( GetChassisCost() + GetEquipCost() ) * GetCostMult() * GetConfigMultiplier()); //+ GetAmmoCosts();
+        return ((GetChassisCost() + GetEquipCost() ) * GetCostMult() * GetConfigMultiplier()) + GetAmmoCosts();
     }
     
     public double GetDryCost() {
         // returns the total cost of the mech without ammunition
-        return ( GetEquipCost() + GetChassisCost() ) * GetCostMult() * GetConfigMultiplier();
+        return (GetEquipCost() + GetChassisCost()) * GetCostMult() * GetConfigMultiplier();
     }
```
Comment (WEKarnesky) [inline sswlib/src/main/java/components/CombatVehicle.java]: Next time this area is touched, we should just have `GetTotalCost` reference `GetDryCost` to minimize Code Duplication

File: sswlib/src/main/java/components/Mech.java [hunk 2]
```diff
@@ -3165,12 +3165,12 @@ public double GetChassisCost() {
...
         // final cost calculations
-        return ( GetEquipCost() + GetChassisCost() ) * GetCostMult();
+        return ((GetEquipCost() + GetChassisCost()) * GetCostMult()) + GetAmmoCosts();
     }
 
     public double GetDryCost() {
         // returns the total cost of the mech without ammunition
-        return ( GetEquipCost() + GetChassisCost() ) * GetCostMult();
+        return (GetEquipCost() + GetChassisCost()) * GetCostMult();
     }
```
Comment (WEKarnesky) [inline sswlib/src/main/java/components/Mech.java]: Like with the vehicles, Next time this area is touched, `GetTotalCost` should reference `GetDryCost` to minimize code duplication.

File: sswlib/src/main/java/Print/PrintVehicle.java [hunk 3]
```diff
@@ -414,7 +414,8 @@ private void DrawMechData( Graphics2D graphics ) {
 
         //Cost
         graphics.setFont( PrintConsts.SmallFont );
-        graphics.drawString( String.format( "%1$,.0f C-Bills", Math.floor( CurVee.GetTotalCost() + 0.5f ) ), p[PrintConsts.COST].x, p[PrintConsts.COST].y );
+        graphics.drawString( String.format("%1$,.0f C-Bills", CurVee.GetTotalCost()), p[PrintConsts.COST].x, p[PrintConsts.COST].y);
+        graphics.drawString( String.format("+%1$,.0f (ammo)", CurVee.GetAmmoCosts()), p[PrintConsts.AMMO].x, p[PrintConsts.AMMO].y);
```
Comment (WEKarnesky) [inline sswlib/src/main/java/Print/PrintVehicle.java]: This does not handle VTOLs, so the VTOL output will not match the Ground Vehicles and 'Mechs.

Comment (KaydenMiller) [reply sswlib/src/main/java/Print/PrintVehicle.java]: Ah, didn't catch that. I will go and update VTOL's.

Comment (KaydenMiller) [reply sswlib/src/main/java/Print/PrintVehicle.java]: Now that i think about it, this probably doesn't cover naval as well.

File: sswlib/src/main/java/components/Mech.java (hunk 2 above)
Comment (KaydenMiller) [reply sswlib/src/main/java/components/Mech.java]: I can update these when I add VTOL.

File: sswlib/src/main/java/components/CombatVehicle.java (hunk 1 above)
Comment (KaydenMiller) [reply sswlib/src/main/java/components/CombatVehicle.java]: I can update these when I add VTOL.

File: sswlib/src/main/java/Print/PrintVehicle.java (hunk 3 above)
Comment (KaydenMiller) [reply sswlib/src/main/java/Print/PrintVehicle.java]: Apparently VTOL and Naval count as CombatVechiles so they would have output but not correctly and if someone had tried to print the PDF it would have given them an out of bounds exception.
